=== alter-eco/ae-xml/xsd/publication.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:ns1='https://www.alternatives-economiques.fr/' elementFormDefault='qualified' targetNamespace='https://www.alternatives-economiques.fr/'>
    <xs:element name='NewsItem'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:rightsInfo'/>
                <xs:element ref='ns1:itemMeta'/>
                <xs:element ref='ns1:contentMeta'/>
                <xs:element ref='ns1:contentSet'/>
                <xs:element ref='ns1:groupSet'/>
            </xs:sequence>
            <xs:attribute name='id' use='required' type='xs:NCName'/>
            <xs:attribute name='standard' use='required' type='xs:NCName'/>
            <xs:attribute name='version' use='required' type='xs:integer'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='rightsInfo'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:copyrightHolder'/>
                <xs:element ref='ns1:copyrightNotice'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='copyrightHolder' type='xs:string'/>
    <xs:element name='copyrightNotice' type='xs:string'/>
    <xs:element name='itemMeta'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:itemClass'/>
                <xs:element ref='ns1:publisher'/>
                <xs:element ref='ns1:pubStatus'/>
                <xs:element ref='ns1:versionCreated'/>
                <xs:element ref='ns1:embargoed'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='itemClass'>
        <xs:complexType>
            <xs:attribute name='type' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='publisher'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:name'/>
                <xs:element ref='ns1:uri'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='name' type='xs:string'/>
    <xs:element name='pubStatus' type='xs:NCName'/>
    <xs:element name='versionCreated' type='xs:NMTOKEN'/>
    <xs:element name='embargoed' type='xs:NMTOKEN'/>
    <xs:element name='contentMeta'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:created'/>
                <xs:element ref='ns1:modified'/>
                <xs:element ref='ns1:title'/>
                <xs:element ref='ns1:price'/>
                <xs:element ref='ns1:issue'/>
                <xs:element ref='ns1:issueDate'/>
                <xs:element ref='ns1:figure'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='created' type='xs:NMTOKEN'/>
    <xs:element name='modified' type='xs:NMTOKEN'/>
    <xs:element name='title' type='xs:string'/>
    <xs:element name='price' type='xs:decimal'/>
    <xs:element name='issue' type='xs:integer'/>
    <xs:element name='issueDate' type='xs:NMTOKEN'/>
    <xs:element name='figure'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:copyright'/>
                <xs:element ref='ns1:caption'/>
                <xs:element ref='ns1:uri'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='copyright' type='xs:NCName'/>
    <xs:element name='caption' type='xs:string'/>
    <xs:element name='contentSet'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:inlineXML'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='inlineXML'>
        <xs:complexType>
            <xs:attribute name='contenttype' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='groupSet'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:group'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='group'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='ns1:itemRef'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='itemRef'>
        <xs:complexType>
            <xs:attribute name='id' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='uri' type='xs:anyURI'/>
</xs:schema>

=== alter-eco/ae-xml/examples/publication/A382.xml
<?xml version="1.0" encoding="utf-8"?>
<NewsItem 
  xmlns="https://www.alternatives-economiques.fr/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.alternatives-economiques.fr/ ../../xsd/publication.xsd"
  standard="AE-XML"

  id="A382"
  version="1"
  >
  <rightsInfo>
    <copyrightHolder>
      Alternatives Economiques
    </copyrightHolder>
    <copyrightNotice>
      Copyright 2018 Alternatives Economiques - Toute reproduction, même partielle, des textes, infographies et documents parus est soumis à l'autorisation préalable de l'éditeur.
    </copyrightNotice>
  </rightsInfo>
  <itemMeta>
    <itemClass type="publication"/>
    <publisher>
      <name>Alternatives Economiques</name>
      <uri>https://www.alternatives-economiques.fr</uri>
    </publisher>
    <pubStatus>usable</pubStatus>
    <versionCreated>YYYY-MM-DDTHH:MM:SS</versionCreated>
    <embargoed>YYYY-MM-DDTHH:MM:SSZ</embargoed>
  </itemMeta>
  <contentMeta>
    <created>YYYY-MM-DDTHH:MM:SS</created>
    <modified>YYYY-MM-DDTHH:MM:SS</modified>
    <title>Faut-il encore avoir peur de la finance ?</title>
    <price>5.90</price>
    <issue>382</issue>
    <issueDate>YYYY-MM-DDTHH:MM:SS</issueDate>
    <figure>
      <copyright>iStock</copyright>
      <caption>Lorem ipsum dolor sit amet</caption>
      <uri>path/to/file.jpg</uri>
    </figure>
  </contentMeta>
  <contentSet>
    <inlineXML contenttype="text/html"></inlineXML>
  </contentSet>
  <groupSet>
    <group>
      <itemRef id="A382-005-A" />
      <itemRef id="A382-007-A" />
      <itemRef id="A382-010-A" />
      <itemRef id="A382-010-B" />
      <itemRef id="A382-012-A" />
      <itemRef id="A382-014-A" />
      <itemRef id="A382-016-A" />
      <itemRef id="A382-018-A" />
      <itemRef id="A382-022-A" />
      <itemRef id="A382-024-A" />
      <itemRef id="A382-026-A" />
      <itemRef id="A382-027-A" />
      <itemRef id="A382-030-A" />
      <itemRef id="A382-031-C" />
      <itemRef id="A382-031-D" />
      <itemRef id="A382-032-A" />
      <itemRef id="A382-035-A" />
      <itemRef id="A382-036-A" />
      <itemRef id="A382-038-A" />
      <itemRef id="A382-040-A" />
      <itemRef id="A382-043-A" />
      <itemRef id="A382-044-A" />
      <itemRef id="A382-046-A" />
      <itemRef id="A382-046-B" />
      <itemRef id="A382-048-A" />
      <itemRef id="A382-051-A" />
      <itemRef id="A382-052-A" />
      <itemRef id="A382-054-A" />
      <itemRef id="A382-056-A" />
      <itemRef id="A382-059-A" />
      <itemRef id="A382-060-A" />
      <itemRef id="A382-060-B" />
      <itemRef id="A382-063-A" />
      <itemRef id="A382-064-A" />
      <itemRef id="A382-068-A" />
      <itemRef id="A382-071-A" />
      <itemRef id="A382-073-A" />
      <itemRef id="A382-076-A" />
      <itemRef id="A382-078-A" />
      <itemRef id="A382-080-A" />
      <itemRef id="A382-081-A" />
      <itemRef id="A382-082-A" />
      <itemRef id="A382-083-A" />
      <itemRef id="A382-092-A" />
      <itemRef id="A382-094-A" />
      <itemRef id="A382-096-A" />
      <itemRef id="A382-098-A" />
    </group>
  </groupSet>
</NewsItem>

=== alter-eco/ae-xml/examples/publication/K4-10001.xml
<?xml version="1.0" encoding="utf-8"?>
<NewsItem xmlns="https://www.alternatives-economiques.fr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.alternatives-economiques.fr https://cdn.jsdelivr.net/gh/alter-eco/ae-xml@0.1.0-alpha/xsd/publication.xsd" standard="AE-XML" id="K4-10001" version="1">
  <rightsInfo>
    <copyrightHolder>
      Alternatives Economiques
    </copyrightHolder>
    <copyrightNotice>
      Copyright 2018 Alternatives Economiques - Toute reproduction, même partielle, des textes, infographies et documents parus est soumis à l'autorisation préalable de l'éditeur.
    </copyrightNotice>
  </rightsInfo>
  <itemMeta>
    <itemClass type="publication"/>
  </itemMeta>
  <contentMeta>
    <created>2018-10-29T09:30:10Z</created>
    <modified>2018-10-29T09:30:10Z</modified>
    <publicationId>AE</publicationId>
    <title>Faut-il encore avoir peur de la finance ?</title>
    <price>5.90</price>
    <issueNumber>382</issueNumber>
    <issueDate>2018-10-29</issueDate>
    <figure>
      <copyright>iStock</copyright>
      <caption>Lorem ipsum dolor sit amet</caption>
      <uri>https://images.pexels.com/photos/459793/pexels-photo-459793.jpeg</uri>
    </figure>
  </contentMeta>
  <contentSet>
    <HTML5/>
  </contentSet>
  <itemSet>
      <itemRef residref="K4-XXXXXX"/>
      <itemRef residref="K4-XXXXXX"/>
      <itemRef residref="K4-XXXXXX"/>
      <itemRef residref="K4-XXXXXX"/>
  </itemSet>
</NewsItem>
