=== alter-eco/ae-xml/xsd/short.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Derived using MOSO Xmplify 1.8.3 by Laurence on 2018-10-18 14:22:05 +0000 -->
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:ns1='https://www.alternatives-economiques.fr/' elementFormDefault='qualified' targetNamespace='https://www.alternatives-economiques.fr/'>
    <xs:element name='NewsItem'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:rightsInfo'/>
                <xs:element ref='ns1:itemMeta'/>
                <xs:element ref='ns1:contentMeta'/>
                <xs:element ref='ns1:contentSet'/>
            </xs:sequence>
            <xs:attribute name='id' use='required' type='xs:NCName'/>
            <xs:attribute name='standard' use='required' type='xs:NCName'/>
            <xs:attribute name='version' use='required' type='xs:integer'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='rightsInfo'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:copyrightHolder'/>
                <xs:element ref='ns1:copyrightNotice'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='copyrightHolder' type='xs:string'/>
    <xs:element name='copyrightNotice' type='xs:string'/>
    <xs:element name='itemMeta'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:parentPublication'/>
                <xs:element ref='ns1:parentItem'/>
                <xs:element ref='ns1:itemClass'/>
                <xs:element ref='ns1:publisher'/>
                <xs:element ref='ns1:pubStatus'/>
                <xs:element ref='ns1:versionCreated'/>
                <xs:element ref='ns1:embargoed'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='parentPublication'>
        <xs:complexType>
            <xs:attribute name='id' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='parentItem'>
        <xs:complexType>
            <xs:attribute name='id' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='itemClass'>
        <xs:complexType>
            <xs:attribute name='type' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='publisher'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:name'/>
                <xs:element ref='ns1:uri'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='name' type='xs:string'/>
    <xs:element name='pubStatus' type='xs:NCName'/>
    <xs:element name='versionCreated' type='xs:NMTOKEN'/>
    <xs:element name='embargoed' type='xs:NMTOKEN'/>
    <xs:element name='contentMeta'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:created'/>
                <xs:element ref='ns1:modified'/>
                <xs:element ref='ns1:title'/>
                <xs:element ref='ns1:genre'/>
                <xs:sequence minOccurs='0'>
                    <xs:element ref='ns1:unit'/>
                    <xs:element ref='ns1:source'/>
                </xs:sequence>
                <xs:element minOccurs='0' ref='ns1:figure'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='created' type='xs:NMTOKEN'/>
    <xs:element name='modified' type='xs:NMTOKEN'/>
    <xs:element name='title' type='xs:string'/>
    <xs:element name='genre' type='xs:NCName'/>
    <xs:element name='unit' type='xs:string'/>
    <xs:element name='source' type='xs:string'/>
    <xs:element name='figure'>
        <xs:complexType>
            <xs:sequence>
                <xs:sequence minOccurs='0'>
                    <xs:element ref='ns1:caption'/>
                    <xs:element ref='ns1:copyright'/>
                </xs:sequence>
                <xs:element ref='ns1:uri'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='caption'>
        <xs:complexType/>
    </xs:element>
    <xs:element name='copyright'>
        <xs:complexType/>
    </xs:element>
    <xs:element name='contentSet'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ns1:inlineXML'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='inlineXML'>
        <xs:complexType mixed='true'>
            <xs:attribute name='contenttype' use='required'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='uri' type='xs:anyURI'/>
</xs:schema>

=== alter-eco/ae-xml/examples/short/encadre/K4-10020 (A382067A.XEC).xml
<?xml version="1.0" encoding="utf-8"?>
<NewsItem xmlns="https://www.alternatives-economiques.fr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.alternatives-economiques.fr ../../../xsd/short.xsd" standard="AE-XML" id="K4-10020" version="1">
  <rightsInfo>
    <copyrightHolder>
      Alternatives Economiques
    </copyrightHolder>
    <copyrightNotice>
      Copyright 2018 Alternatives Economiques - Toute reproduction, même partielle, des textes, infographies et documents parus est soumis à l'autorisation préalable de l'éditeur.
    </copyrightNotice>
  </rightsInfo>
  <itemMeta>
    <parentPublication id="A382"/>
    <parentItem id="A382-064-A"/>
    <itemClass type="short"/>
    <embargoed>2018-11-29T09:30:10Z</embargoed>
  </itemMeta>
  <contentMeta>
    <created>2018-10-29T09:30:10Z</created>
    <modified>2018-10-29T09:30:10Z</modified>
    <title>1929, 2008, même combat</title>
    <genre>encadré</genre>
  </contentMeta>
  <contentSet>
    <inlineXML contenttype="text/html"><![CDATA[
        <p>Au-delà de leurs dimensions particulières, les crises de 1929 et de 2007-2008 s’avèrent très comparables. Innovation financière majeure, de nouvelles sociétés d’investissement sont créées dans les années 1920 pour faciliter les placements risqués en Bourse. Il y en avait 160 en 1926 et 750 en 1929. En concurrence avec les filiales de marchés financiers des banques commerciales, elles font exploser les placements spéculatifs. Le volume d’échange à la Bourse de New York passe de 236 millions d’actions en 1923 à 1,1 milliard en 1929. Des placements soutenus par une bulle de crédits : entre 1921 et 1930, la croissance annuelle moyenne des prêts garantis par la valeur des actions détenues par les emprunteurs a été de 98 % ! Le tout avec des régulateurs absents et un ministre des Finances, Andrew W. Mellon, ultralibéral avant l’heure, confiant dans l’autorégulation des marchés. Les années 1920 ont aussi été celles des fraudeurs, à l’image de Carlo Ponzi, qui laissera son nom au système consistant à rémunérer fortement les premiers investisseurs avec l’argent reçu des suivants pour en attirer de nouveaux. Les enquêtes de la commission dirigée par le magistrat Ferdinand Pecora montreront à l’époque des comportements de fraude généralisée.</p>
        <object type="application/xml" data="A382-067-B.xml"></object>
        <p>De manière étonnante, les niveaux d’inégalité et de dérégulation financière étaient identiques en 1929 et en 2007, soulignant la même dimension sociopolitique de toute crise financière.</p>
      ]]></inlineXML>
  </contentSet>
</NewsItem>

=== alter-eco/ae-xml/examples/short/graphic/A382-011-A.xml
<?xml version="1.0" encoding="utf-8"?>
<NewsItem 
  xmlns="AlterEco"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.alternatives-economiques.fr/ ../../../xsd/short.xsd"
  standard="AE-XML"

  id="A382-011-A"
  version="1"
  >
  <rightsInfo>
    <copyrightHolder>
      Alternatives Economiques
    </copyrightHolder>
    <copyrightNotice>
      Copyright 2018 Alternatives Economiques - Toute reproduction, même partielle, des textes, infographies et documents parus est soumis à l'autorisation préalable de l'éditeur.
    </copyrightNotice>
  </rightsInfo>
  <itemMeta>
    <parentPublication id="A382" />
    <parentItem id="A382-010-A" />
    <itemClass type="short"/>
    <embargoed>YYYY-MM-DDTHH:MM:SSZ</embargoed>
  </itemMeta>
  <contentMeta>
    <created>YYYY-MM-DDTHH:MM:SS</created>
    <modified>YYYY-MM-DDTHH:MM:SS</modified>
    <title>Evolution de la dépense par étudiant, des effectifs étudiants, des enseignants titulaires et des enseignants non permanents, base 100 = 2000</title>
    <genre>graphique</genre>
    <unit>Base 100 = 200</unit>
    <source>Ministère de l'Enseignement supérieur et de la Recherche, caluls Alternatives Economiques</source>
    <figure>
      <caption></caption>
      <copyright></copryright>
      <uri>path/to/file.jpg</uri>
    </figure>
  </contentMeta>
  <contentSet>
    <inlineXML contenttype="text/html"></inlineXML>
  </contentSet>
</NewsItem>

=== alter-eco/ae-xml/examples/short/graphic/K4-10021 (A382011A.XGP).xml
<?xml version="1.0" encoding="utf-8"?>
<NewsItem xmlns="https://www.alternatives-economiques.fr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="https://www.alternatives-economiques.fr ../../../xsd/short.xsd" standard="AE-XML" id="K4-10021" version="1">
  <rightsInfo>
    <copyrightHolder>
      Alternatives Economiques
    </copyrightHolder>
    <copyrightNotice>
      Copyright 2018 Alternatives Economiques - Toute reproduction, même partielle, des textes, infographies et documents parus est soumis à l'autorisation préalable de l'éditeur.
    </copyrightNotice>
  </rightsInfo>
  <itemMeta>
    <parentPublication xlink:href="K4-10001.xml"/>
    <parentItem xlink:href="K4-XXXXX.xml" />
    <itemClass type="short"/>
    <embargoed>2018-11-29T09:30:10Z</embargoed>
  </itemMeta>
  <contentMeta>
    <created>2018-10-29T09:30:10Z</created>
    <modified>2018-10-29T09:30:10Z</modified>
    <title>Evolution de la dépense par étudiant, des effectifs étudiants, des enseignants titulaires et des enseignants non permanents, base 100 = 2000</title>
    <genre>graphique</genre>
    <source>Ministère de l'Enseignement supérieur et de la Recherche, caluls Alternatives Economiques</source>
    <unit>Base 100 = 200</unit>
    <figure>
      <caption/>
      <copyright/>
      <uri>path/to/file.jpg</uri>
    </figure>
  </contentMeta>
  <contentSet>
    <inlineXML contenttype="text/html"/>
  </contentSet>
</NewsItem>

=== alter-eco/ae-xml/examples/short/graphic/K4-10022 (A382065A.XGP).xml
<?xml version="1.0" encoding="utf-8"?>
<NewsItem xmlns="https://www.alternatives-economiques.fr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="https://www.alternatives-economiques.fr https://cdn.jsdelivr.net/gh/alter-eco/ae-xml@0.0.3-alpha/xsd/short.xsd" standard="AE-XML" id="K4-10022" version="1">
  <rightsInfo>
    <copyrightHolder>
      Alternatives Economiques
    </copyrightHolder>
    <copyrightNotice>
      Copyright 2018 Alternatives Economiques - Toute reproduction, même partielle, des textes, infographies et documents parus est soumis à l'autorisation préalable de l'éditeur.
    </copyrightNotice>
  </rightsInfo>
  <itemMeta>
    <parentPublication xlink:href="K4-10001.xml"/>
    <parentItem xlink:href="K4-XXXXX.xml"/>
    <itemClass type="short"/>
    <embargoed>2018-11-29T09:30:10Z</embargoed>
  </itemMeta>
  <contentMeta>
    <created>2018-10-29T09:30:10Z</created>
    <modified>2018-10-29T09:30:10Z</modified>
    <title>Le grand cycle des crises</title>
    <genre>graphique</genre>
    <figure>
      <caption/>
      <copyright/>
      <uri><![CDATA[https://images.unsplash.com/photo-1546704259-d4dac118f426?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb]]></uri>
    </figure>
  </contentMeta>
  <contentSet>
    <HTML5/>
  </contentSet>
</NewsItem>

=== alter-eco/ae-xml/examples/short/graphic/A382-065-A.xml
<?xml version="1.0" encoding="utf-8"?>
<NewsItem 
  xmlns="AlterEco"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.alternatives-economiques.fr/ ../../../xsd/short.xsd"
  standard="AE-XML"

  id="A382-065-A"
  version="1"
  >
  <rightsInfo>
    <copyrightHolder>
      Alternatives Economiques
    </copyrightHolder>
    <copyrightNotice>
      Copyright 2018 Alternatives Economiques - Toute reproduction, même partielle, des textes, infographies et documents parus est soumis à l'autorisation préalable de l'éditeur.
    </copyrightNotice>
  </rightsInfo>
  <itemMeta>
    <parentPublication id="A382" />
    <parentItem id="A382-064-A" />
    <itemClass type="short"/>
    <embargoed>YYYY-MM-DDTHH:MM:SSZ</embargoed>
  </itemMeta>
  <contentMeta>
    <created>YYYY-MM-DDTHH:MM:SS</created>
    <modified>YYYY-MM-DDTHH:MM:SS</modified>
    <title>Le grand cycle des crises</title>
    <genre>graphique</genre>
    <figure>
      <uri>path/to/file.jpg</uri>
    </figure>
  </contentMeta>
  <contentSet>
    <inlineXML contenttype="text/html"></inlineXML>
  </contentSet>
</NewsItem>

=== alter-eco/ae-xml/examples/short/breve/A382-008-A.xml
<?xml version="1.0" encoding="utf-8"?>
<NewsItem 
  xmlns="https://www.alternatives-economiques.fr/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.alternatives-economiques.fr/ ../../../xsd/short.xsd"
  standard="AE-XML"

  id="A382-008-A"
  version="1"
  >
  <rightsInfo>
    <copyrightHolder>
      Alternatives Economiques
    </copyrightHolder>
    <copyrightNotice>
      Copyright 2018 Alternatives Economiques - Toute reproduction, même partielle, des textes, infographies et documents parus est soumis à l'autorisation préalable de l'éditeur.
    </copyrightNotice>
  </rightsInfo>
  <itemMeta>
    <parentPublication id="A382" />
    <itemClass type="short"/>
    <publisher>
      <name>Alternatives Economiques</name>
      <uri>https://www.alternatives-economiques.fr</uri>
    </publisher>
    <pubStatus>usable</pubStatus>
    <versionCreated>YYYY-MM-DDTHH:MM:SS</versionCreated>
    <embargoed>YYYY-MM-DDTHH:MM:SSZ</embargoed>
  </itemMeta>
  <contentMeta>
    <created>YYYY-MM-DDTHH:MM:SS</created>
    <modified>YYYY-MM-DDTHH:MM:SS</modified>
    <title>En voiture Simone</title>
    <section>Buzz</section>
    <genre>brève</genre>
  </contentMeta>
  <contentSet>
    <inlineXML contenttype="text/html">
      <![CDATA[
        <p>Le Conseil d'Etat a validé fin juillet une large partie du plan autoroutier décidé par François Hollande en 2016. Il permettra de construire, entre autres, 23 nouveaux échangeurs comme de réaménager le périphérique de Nantes. Montant des travaux&nbsp;: 700 millions d'euros, financés à moitié par les collectivités locales et à moitié par une hausse des péages. Cette opération, qui succède à un autre plan de 3,2 milliards d'euros adopté en 2015, n'a pas rassasié les concessionnaires, qui espèrent déjà un troisième plan. <em>Let's make our C02 emissions great again&nbsp;!</em></p>
      ]]>
    </inlineXML>
  </contentSet>
</NewsItem>
